sudo: required
services:
  - docker

before_install:
  - docker build -t austenvalentine/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run austenvalentine/react-test npm run test -- --coverage

after_success:
  - docker build -t austenvalentine/multi-client ./client
  - docker build -t austenvalentine/multi-worker ./worker
  - docker build -t austenvalentine/multi-nginx ./nginx
  - docker build -t austenvalentine/multi-server ./server
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ## push those images to travis CI .
  - docker push austenvalentine/multi-client
  - docker push austenvalentine/multi-nginx
  - docker push austenvalentine/multi-worker
  - docker push austenvalentine/multi-server